apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.wsgc.com/TS-ContainerServices/k8s-platform-addons-base/kube-state-metrics/base/
- deployment.yaml
- service.yaml
images:
  - name: quay.io/coreos/kube-state-metrics
    newTag: v1.9.8
patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: kube-state-metrics
    namespace: kube-system
  spec:
    template:
      spec:
        containers:
          - name: kube-state-metrics
            imagePullPolicy: IfNotPresent
- |-
  apiVersion: v1
  kind: Service
  metadata:
    name: kube-state-metrics
    namespace: kube-system
  spec:
    clusterIP: null
