{{- if .Values.nodeport.enabled }}
  {{- $fullName := include "cp-kafka.fullname" . }}
  {{- $brokers := .Values.brokers | int }}
  {{- $servicePort := .Values.nodeport.servicePort }}
  {{- $authservicePort := .Values.nodeport.authservicePort }}
  {{- $root := . }}
  {{- range $i, $e := until $brokers }}
    {{- $externalListenerPort := add $root.Values.nodeport.firstListenerPort $i }}
    {{- $responsiblePod := printf "%s-%d" (printf "%s" $fullName) $i }}
    {{- $externalPlaintextListenerPort := add $root.Values.nodeport.plaintextListenerPort $i }}
    {{- $externalauthListenerPort := add $root.Values.nodeport.externalauthListenerPort $i }}
    {{- $externalPrometheusListenerPort := add $root.Values.nodeport.prometheusListenerPort $i }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $root.Release.Name }}-{{ $i }}-nodeport
  labels:
    app: {{ include "cp-kafka.name" $root }}
    chart: {{ template "cp-kafka.chart" $root }}
    release: {{ $root.Release.Name }}
    heritage: {{ $root.Release.Service }}
    pod: {{ $responsiblePod }}
spec:
  type: NodePort
  ports:
    - name: externalplaintext-broker
      port: 9092
      targetPort: {{ $externalPlaintextListenerPort }}
      nodePort: {{ $externalPlaintextListenerPort }}
      protocol: TCP
    - name: external-broker
      port: {{ $servicePort }}
      targetPort: {{ $externalListenerPort }}
      nodePort: {{ $externalListenerPort }}
      protocol: TCP
    - name: external-auth-broker
      port: 19093
      targetPort: {{ $externalauthListenerPort }}
      nodePort: {{ $externalauthListenerPort }}
      protocol: TCP
    - name: external-prometheus-broker
      port: {{ $root.Values.prometheus.jmx.port }}
      targetPort: {{ $root.Values.prometheus.jmx.port }}
      nodePort: {{ $externalPrometheusListenerPort }}
      protocol: TCP
  selector:
    app: {{ include "cp-kafka.name" $root }}
    release: {{ $root.Release.Name }}
    statefulset.kubernetes.io/pod-name: {{ $responsiblePod | quote }}
  {{- end }}
{{- end }}