apiVersion: v1
kind: Pod
metadata:
      name: kafka-client
      namespace: lms-kafka-dev
spec:
  containers:
  - name: kafka-client
    image: container-registry01.nonprod.wsgc.com/integration/cp-kafka:6.0.1.2wsi
    command:
      - sh
      - -c
      - "exec tail -f /dev/null"
